# Generated by Django 6.0.7 on 2026-08-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                        default="นาย",
                        max_length=10,
                    ),
                ),
                ("st_id", models.CharField(max_length=12, unique=True)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
            ],
        ),
    ]
