# Generated by Django 6.0.7 on 2026-08-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="st_id",
            new_name="stu_id",
        ),
    ]
